# Copyright SduNetCheckTool
# Licensed under the GNU General Public License v3.0

name: Release
on:
  [release, workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Build
          run: |
            echo "Building..."
            echo "Build complete."        
        
        - name: Create Release
          uses: softprops/action-gh-release@v1
          with:
            files: |
                build/${{ env.appPackagesArchive }}
                build/SduNetCheckTool.GUI_boxed.exe
                LICENSE.txt
            tag_name: 0.0.1
            body: |
                This is an automated release of this Wpf application.
            draft: false
            prerelease: false
            token: ${{secrets.GITHUB_TOKEN}}